// Only these non-secret settings may be packed. Feature switches, secrets and
// values read outside getConsumerConfig remain separate environment bindings.
export const PACKABLE_CONSUMER_SETTINGS = Object.freeze([
  "CONSUMER_AGENT_TEST_COHORTS",
  "CONSUMER_ALLOWED_MODULE_IDS",
  "CONSUMER_MODULE_PLANNER_PROMPT_VERSION",
  "CONSUMER_MODULE_VERIFIER_PROMPT_VERSION",
  "CONSUMER_COHORT",
  "CONSUMER_CONSENT_POLICY_VERSION",
  "CONSUMER_CONSENT_MANIFEST_ID",
  "CONSUMER_ANALYSIS_NOTICE_ID",
  "CONSUMER_AI_NOTICE_ID",
  "CONSUMER_VOICE_NOTICE_ID",
  "CONSUMER_PRIVACY_NOTICE_URL",
  "CONSUMER_SESSION_TTL_DAYS",
  "CONSUMER_MAX_MESSAGE_LENGTH",
  "CONSUMER_MAX_TURNS_PER_SESSION",
  "CONSUMER_INVITE_MAX_TTL_HOURS",
  "CONSUMER_AI_DATA_POLICY_ID",
  "CONSUMER_VOICE_DATA_POLICY_ID",
  "CONSUMER_VOICE_TRANSCRIPTION_MODEL",
  "CONSUMER_VOICE_SPEECH_MODEL",
  "CONSUMER_VOICE_NAME",
  "CONSUMER_VOICE_PRICING_VERSION",
  "CONSUMER_VOICE_TIMEOUT_MS",
  "CONSUMER_VOICE_MAX_AUDIO_BYTES",
  "CONSUMER_VOICE_MAX_DURATION_SECONDS",
  "CONSUMER_VOICE_MAX_SPEECH_CHARACTERS",
  "CONSUMER_VOICE_SESSION_BUDGET_EUR_CENTS",
  "CONSUMER_VOICE_DAILY_BUDGET_EUR_CENTS",
  "CONSUMER_VOICE_TRANSCRIPTION_RESERVATION_EUR_CENTS",
  "CONSUMER_VOICE_SPEECH_RESERVATION_EUR_CENTS",
  "CONSUMER_REALTIME_NOTICE_ID",
  "CONSUMER_REALTIME_DATA_POLICY_ID",
  "CONSUMER_REALTIME_MODEL",
  "CONSUMER_REALTIME_VOICE",
  "CONSUMER_REALTIME_REASONING_EFFORT",
  "CONSUMER_REALTIME_TRANSCRIPTION_MODEL",
  "CONSUMER_REALTIME_PROMPT_VERSION",
  "CONSUMER_REALTIME_TOOLSET_VERSION",
  "CONSUMER_REALTIME_PRICING_VERSION",
  "CONSUMER_REALTIME_SESSION_BUDGET_EUR_CENTS",
  "CONSUMER_REALTIME_SESSION_WARN_EUR_CENTS",
  "CONSUMER_REALTIME_DAILY_BUDGET_EUR_CENTS",
  "CONSUMER_REALTIME_MAX_DURATION_SECONDS",
  "CONSUMER_REALTIME_IDLE_TIMEOUT_SECONDS",
  "CONSUMER_REALTIME_SILENCE_PROMPT_SECONDS",
  "CONSUMER_REALTIME_MAX_SDP_BYTES",
  "CONSUMER_REALTIME_MAX_RESPONSES",
  "CONSUMER_REALTIME_MAX_TOOL_CALLS",
  "CONSUMER_REALTIME_PLANNER_TIMEOUT_MS",
  "CONSUMER_REALTIME_PLANNER_CATCHUP_TIMEOUT_MS",
  "CONSUMER_REALTIME_PLANNER_PROMPT_VERSION",
  "CONSUMER_PLANNER_RECONCILIATION_PROMPT_VERSION",
  "CONSUMER_REALTIME_PLANNER_MODEL",
  "CONSUMER_REALTIME_TEXT_INPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_TEXT_CACHED_INPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_TEXT_OUTPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_AUDIO_INPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_AUDIO_CACHED_INPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_AUDIO_OUTPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_TRANSCRIPTION_INPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_TRANSCRIPTION_OUTPUT_EUR_MICROS_PER_MILLION",
  "CONSUMER_REALTIME_SPEECH_EUR_MICROS_PER_MILLION_CHARACTERS",
  "CONSUMER_AI_COMPLEX_MODEL",
  "CONSUMER_AI_DEFAULT_REASONING_EFFORT",
  "CONSUMER_AI_COMPLEX_REASONING_EFFORT",
  "CONSUMER_AI_PROMPT_VERSION",
  "CONSUMER_AI_TIMEOUT_MS",
  "CONSUMER_AI_MAX_OUTPUT_TOKENS",
  "CONSUMER_AI_REQUEST_TOKEN_RESERVATION",
  "CONSUMER_AI_SESSION_REQUEST_BUDGET",
  "CONSUMER_AI_DAILY_REQUEST_BUDGET",
  "CONSUMER_AI_COMPLEX_SESSION_REQUEST_BUDGET",
  "CONSUMER_AI_COMPLEX_DAILY_REQUEST_BUDGET",
  "CONSUMER_AI_SESSION_TOKEN_BUDGET",
  "CONSUMER_AI_DAILY_TOKEN_BUDGET",
  "CONSUMER_HANDOFF_POLICY_VERSION",
  "CONSUMER_HANDOFF_POLICY_URL",
  "CONSUMER_HANDOFF_RETENTION_POLICY_ID",
  "CONSUMER_HANDOFF_RETENTION_DAYS",
  "CONSUMER_BOOKING_URL"
]);
const allowed = new Set(PACKABLE_CONSUMER_SETTINGS);

export function expandConsumerSettings(env) {
  const packed = {};
  let present = false;
  for (let index = 1; index <= 4; index += 1) {
    const raw = env[`CONSUMER_SETTINGS_JSON_${index}`];
    if (raw === undefined) continue;
    present = true;
    if (typeof raw !== 'string' || new TextEncoder().encode(raw).byteLength > 4096) throw new Error('Invalid packed consumer settings.');
    let values;
    try { values = JSON.parse(raw); } catch { throw new Error('Invalid packed consumer settings.'); }
    if (!values || typeof values !== 'object' || Array.isArray(values)) throw new Error('Invalid packed consumer settings.');
    for (const [name, value] of Object.entries(values)) {
      if (!allowed.has(name) || typeof value !== 'string' || Object.hasOwn(packed, name)) throw new Error('Invalid packed consumer settings.');
      packed[name] = value;
    }
  }
  // Explicit variables retain precedence for ordinary operational overrides.
  return present ? { ...packed, ...env } : env;
}
