/**
 * THE ARCHIVED COMPARISON LANE'S APPROVAL READER. NOT THE PRODUCTION ONE.
 *
 * Read this before reusing anything here. Until 14 September 2026 this decided
 * whether a client's words authorised execution on every lane, and Astra's
 * independent audit found three P1 bypasses in it that no vocabulary fix
 * reaches:
 *
 *   - It never knew WHAT THE CLIENT WAS ANSWERING. After a clarification
 *     exchange the last assistant question is often not the certified plan, and
 *     a "yes" to that question read identically to a "yes" to the plan.
 *   - `[^a-z0-9\s]` -> ' ' DELETES every character outside the Latin alphabet
 *     before anything weighs the words, so a reply that agreed in English and
 *     then corrected an owner in another script normalised to "yes".
 *   - A grammar cannot weigh a condition, an exclusion, or a withdrawn
 *     certainty at all. Those are judgements about meaning in context.
 *
 * Under direct apply -- what production runs -- the decision now belongs to a
 * bounded AI reader in ./approval_decision.js, which is given the complete
 * reply, the exact assistant utterance it answered and the exact delivered
 * certified offer. Deterministic code there enforces only control facts.
 *
 * This file survives for the archived comparison lane, which is not the target
 * architecture and is not deployed. Do not reintroduce it to the direct path,
 * and do not treat its dictionaries as a model of what approval means.
 *
 * What it does, for that lane: recognises complete approval clauses, with
 * ordinary Irish and conversational combinations, rather than requiring every
 * token to be in a shared allowlist. Anything outside that bounded interaction
 * goes back to the existing background planner while the offered plan remains
 * provisional. ASR punctuation is generated by a model and carries no approval
 * authority.
 */
function normalizedApproval(value) {
  return String(value || '')
    .normalize('NFKC')
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const REFUSAL = /^(?:no|nope|no thanks|no thank you|not now|please stop|stop|dont proceed|do not proceed)$/;
const NEGATION_OR_CHANGE = /\b(?:no|nope|not|never|dont|doesnt|didnt|cant|cannot|wont|wouldnt|shouldnt|isnt|arent|wasnt|werent|wait|hold|stop|change|correction|actually|wrong|instead|except|but|rather)\b/;
const CONDITION_OR_UNCERTAINTY = /\b(?:if|unless|provided|providing|assuming|before|after|until|once|when|maybe|perhaps|probably|possibly|roughly|about|around|think|guess|suppose|hope|might|uncertain|unsure|seems)\b/;
const LINGUISTIC_QUESTION = /\b(?:why|what|which|who|where|how|whether|question)\b|^(?:can|could|would|should|will|did|does|do you|is it|is that|are you|have you)\b/;

// An affirmative signal must be present; courtesy alone is never approval.
//
// `ja`, `aye`, `ya` and `yah` are here because production put them here. On
// 2026-09-05 a client approved a certified plan and Whisper -- transcribing
// Irish-accented English with language 'en' -- returned "Ja.". The plan was
// refused, the approval turn was then treated as ordinary evidence, and the
// meeting died. None of these four can carry a correction, a figure, a
// question or a hedge, and the whole-clause rule below still refuses anything
// that does, so recognising them costs no safety: "ja but change the pension"
// remains ambiguous because NEGATION_OR_CHANGE sees "but" and "change".
const APPROVAL_SIGNAL = /\b(?:yes|yep|yeah|yup|ya|yah|ja|aye|sure|grand|perfect|absolutely|okay|ok|correct|confirmed|confirm|right|happy|sounds? good|go ahead|go for it|work away|fire away|please do|proceed|do it|run|generate|create)\b/;
const TARGET = '(?:it|(?:the|that|this|those|these) (?:plan|modules|analysis|analyses)|modules|analyses)';
const CLAUSE = new RegExp('^(?:'
  + '(?:yes|yep|yeah|yup|ya|yah|ja|aye|sure|grand|perfect|absolutely|okay|ok|correct|confirmed)'
  + '|(?:that is|thats|its|that sounds|it sounds|sounds|all) (?:correct|right|good)'
  + '|(?:i confirm|im happy with (?:that|it|the plan))'
  + '|(?:please )?(?:go ahead|go for it|work away|fire away|proceed|do it)'
  + '|please do'
  + '|(?:please )?(?:run|generate|create) ' + TARGET
  + '|(?:lets|let us) (?:go ahead|proceed|do it|run ' + TARGET + ')'
  + '|(?:thank you|thanks|please|now)'
  + ')(?= |$)');

export function classifyExecutionApproval(value) {
  const text = normalizedApproval(value);
  if (!text || text.length > 240 || text.split(' ').length > 24) return 'ambiguous';
  if (REFUSAL.test(text)) return 'rejected';
  if (NEGATION_OR_CHANGE.test(text)
    || CONDITION_OR_UNCERTAINTY.test(text)
    || LINGUISTIC_QUESTION.test(text)
    || !APPROVAL_SIGNAL.test(text)) return 'ambiguous';

  // Whole clauses prevent an affirmative prefix from authorising an utterance
  // containing an unreviewed correction, owner, figure or other new content.
  let rest = text;
  for (let count = 0; count < 8 && rest; count += 1) {
    const match = rest.match(CLAUSE);
    if (!match) return 'ambiguous';
    rest = rest.slice(match[0].length).trim().replace(/^and /, '');
  }
  return rest ? 'ambiguous' : 'affirmed';
}
