/**
 * A narrow interaction decision, never a financial interpreter.
 *
 * This gate is deliberately separate from evidence affirmation and the older
 * Realtime lane. It recognises complete approval clauses, with ordinary Irish
 * and conversational combinations, rather than requiring every token to be in
 * a shared allowlist. Anything outside that bounded interaction goes back to
 * the existing background planner while the offered plan remains provisional.
 * ASR punctuation is generated by a model and carries no approval authority.
 */
function normalizedApproval(value) {
  return String(value || '')
    .normalize('NFKC')
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const REFUSAL = /^(?:no|nope|no thanks|no thank you|not now|please stop|stop|dont proceed|do not proceed)$/;
const NEGATION_OR_CHANGE = /\b(?:no|nope|not|never|dont|doesnt|didnt|cant|cannot|wont|wouldnt|shouldnt|isnt|arent|wasnt|werent|wait|hold|stop|change|correction|actually|wrong|instead|except|but|rather)\b/;
const CONDITION_OR_UNCERTAINTY = /\b(?:if|unless|provided|providing|assuming|before|after|until|once|when|maybe|perhaps|probably|possibly|roughly|about|around|think|guess|suppose|hope|might|uncertain|unsure|seems)\b/;
const LINGUISTIC_QUESTION = /\b(?:why|what|which|who|where|how|whether|question)\b|^(?:can|could|would|should|will|did|does|do you|is it|is that|are you|have you)\b/;

// An affirmative signal must be present; courtesy alone is never approval.
const APPROVAL_SIGNAL = /\b(?:yes|yep|yeah|yup|sure|grand|perfect|absolutely|okay|ok|correct|confirmed|confirm|right|happy|sounds? good|go ahead|go for it|work away|fire away|please do|proceed|do it|run|generate|create)\b/;
const TARGET = '(?:it|(?:the|that|this|those|these) (?:plan|modules|analysis|analyses)|modules|analyses)';
const CLAUSE = new RegExp('^(?:'
  + '(?:yes|yep|yeah|yup|sure|grand|perfect|absolutely|okay|ok|correct|confirmed)'
  + '|(?:that is|thats|its|that sounds|it sounds|sounds|all) (?:correct|right|good)'
  + '|(?:i confirm|im happy with (?:that|it|the plan))'
  + '|(?:please )?(?:go ahead|go for it|work away|fire away|proceed|do it)'
  + '|please do'
  + '|(?:please )?(?:run|generate|create) ' + TARGET
  + '|(?:lets|let us) (?:go ahead|proceed|do it|run ' + TARGET + ')'
  + '|(?:thank you|thanks|please|now)'
  + ')(?= |$)');

export function classifyExecutionApproval(value) {
  const text = normalizedApproval(value);
  if (!text || text.length > 240 || text.split(' ').length > 24) return 'ambiguous';
  if (REFUSAL.test(text)) return 'rejected';
  if (NEGATION_OR_CHANGE.test(text)
    || CONDITION_OR_UNCERTAINTY.test(text)
    || LINGUISTIC_QUESTION.test(text)
    || !APPROVAL_SIGNAL.test(text)) return 'ambiguous';

  // Whole clauses prevent an affirmative prefix from authorising an utterance
  // containing an unreviewed correction, owner, figure or other new content.
  let rest = text;
  for (let count = 0; count < 8 && rest; count += 1) {
    const match = rest.match(CLAUSE);
    if (!match) return 'ambiguous';
    rest = rest.slice(match[0].length).trim().replace(/^and /, '');
  }
  return rest ? 'ambiguous' : 'affirmed';
}
